import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "./AuthContext";

const LanguageContext = createContext();

const translations = {
  en: {
    assessment: "Assessment",
    dashboard: "Dashboard",
    askSakhi: "Ask Sakhi",
    clinics: "Clinics",
    resources: "Resources",
    community: "Community",
    english: "English",
    hindi: "Hindi",
    loginSignup: "Login / Sign Up",
    myAccount: "My Account",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    careMenu: "AarogyaShree care menu",
    trustedSakhi: "Your trusted health sakhi",
    heroTitlePrefix: "A gentle, intelligent companion for",
    yourHealth: "Your Health",
    heroCopy:
      "Understand your body, detect early signs, and get guidance in a safe and personal way. Built for every woman across India.",
    startHealthCheck: "Start My Health Check",
    learnMore: "Learn More",
    aiInsights: "AI-powered insights",
    designedForWomen: "Designed for women",
    multilingual: "Multilingual support",
    requiredFirstStep: "Required first step",
    completeQuestionnaire: "Complete your health questionnaire first",
    questionnaireIntro:
      "Sakhi starts with simple required questions so your health overview is based on your symptoms and history. Image upload comes later as an optional support step.",
    takesFewMinutes: "Takes only a few minutes",
    privateRespectful: "Private and respectful",
    startQuestionnaire: "Start Questionnaire",
    assessmentFlow: "Your assessment flow",
    oneGuidedPath: "One guided path",
    answerRequired: "Answer required questions",
    answerRequiredDesc:
      "Symptoms, cycle, breast health, cervical health, mood, and lifestyle.",
    addImageIfNeeded: "Add image if needed",
    addImageIfNeededDesc:
      "Optional final step after the questionnaire. Skip it anytime.",
    getOverview: "Get your health overview",
    getOverviewDesc: "A gentle summary with clear next steps and suggestions.",
    step: "Step",
    optionalImageAfter: "Optional image upload comes after the questionnaire",
    optionalImageCopy:
      "You can upload an image if you want extra AI-assisted guidance. On mobile, Sakhi will also show a camera option.",
    welcomeBack: "Welcome Back Sakhi",
    joinAarogyaShree: "Join AarogyaShree",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    login: "Login",
    signUp: "Sign Up",
    newHere: "New here?",
    createAccount: "Create account",
    alreadyRegistered: "Already registered?",
    authFailedLocal:
      "Backend login is unavailable, so Sakhi saved this session locally.",
    yourSakhi: "Your Sakhi",
    question: "Question",
    of: "of",
    complete: "Complete",
    questionnaireComplete: "Questionnaire complete",
    questionnaireCompleteCopy:
      "Your required answers are ready. You can now add an optional image for extra AI-assisted guidance, or skip it and view your health overview.",
    requiredDone: "Required questions completed",
    imageOptional: "Image upload is optional",
    skipReport: "You can skip to your report",
    addOptionalImage: "Add optional image",
    addOptionalImageCopy:
      "Upload or capture an image if you want additional guidance.",
    continueImage: "Continue to image step",
    skipImageReport: "Skip image and view report",
    skipImageReportCopy:
      "Go directly to your health overview based on the required questionnaire.",
    viewReport: "View my report",
    imageAssessment: "Image-based assessment",
    uploadSafely: "Upload your image safely",
    uploadSafelyCopy:
      "Add a clear image so Sakhi can provide gentle AI-assisted guidance. This is supportive information, not a medical diagnosis.",
    addClearImage: "Add a clear image",
    clearImageCopy:
      "Use good lighting, keep the image steady, and avoid sharing anything you are not comfortable uploading.",
    clickImage: "Click Image",
    uploadImage: "Upload Image",
    cameraMobile: "Camera capture appears on mobile devices.",
    changeImage: "Change image",
    remove: "Remove",
    analyzeImage: "Analyze Image",
    skipImage: "Skip Image",
    beforeUpload: "Before you upload",
    imageTip1: "Use a clear, well-lit image.",
    imageTip2: "Avoid including face or identity details if not needed.",
    imageTip3:
      "Consult a doctor for pain, discharge, bleeding, lumps, or symptoms that persist.",
    gentleInsight: "Sakhi's gentle insight",
    gentleInsightCopy:
      "Based on the image provided, everything appears generally normal in this placeholder preview. If you are experiencing discomfort or changes, consider consulting a healthcare professional.",
    maintainHygiene: "Maintain proper hygiene",
    stayHydrated: "Stay hydrated",
    seekAdvice: "Seek medical advice if symptoms persist",
    continueReport: "Continue to Health Report",
    ageSakhi: "Let me know your age group so I can guide you better.",
    ageQuestion: "What is your age group?",
    previous: "Previous",
    next: "Next",
    menstrualSakhi: "Let's talk about your periods and hormonal health.",
    regularPeriods: "Are your periods regular?",
    cycleLength: "Your usual cycle length?",
    heavyBleeding: "Do you have very heavy bleeding?",
    missedPeriods: "Missed periods for 2+ months (not pregnant)?",
    yes: "Yes",
    no: "No",
    sometimes: "Sometimes",
    cervicalSakhi: "Some questions related to cervical health.",
    abnormalDischarge: "Abnormal vaginal discharge?",
    bleedingBetween: "Bleeding after intercourse or between periods?",
    pelvicPain: "Pelvic or lower abdominal pain?",
    papTest: "Have you ever had a Pap test?",
    never: "Never",
    moreThan3Years: "More than 3 years ago",
    within3Years: "Within last 3 years",
    breastSakhi: "Let's check for any breast-related symptoms.",
    breastLump: "Have you felt any lump in breast or armpit?",
    breastSkin: "Any change in breast skin or shape?",
    nippleDischarge: "Any nipple discharge (not breast milk)?",
    familyHistory: "Family history of breast cancer?",
    notSure: "Not sure",
    generalSakhi: "Some general health questions before we finish.",
    burningUrine: "Burning sensation while urinating?",
    frequentUrge: "Frequent urge to urinate?",
    feverBackPain: "Fever or back pain with urinary problems?",
    moodSakhi: "Last few questions about your mood and daily habits.",
    emotionalFeeling: "How are you feeling emotionally these days?",
    sleepQuestion: "How is your sleep usually?",
    exerciseQuestion: "Do you exercise at least 3 days a week?",
    good: "Good",
    stressed: "Stressed",
    anxious: "Anxious",
    veryLow: "Very low",
    poor: "Poor",
    less21: "<21 days",
    days21to35: "21-35 days",
    more35: ">35 days",
  },
  hi: {
    assessment: "मूल्यांकन",
    dashboard: "डैशबोर्ड",
    askSakhi: "सखी से पूछें",
    clinics: "क्लिनिक",
    resources: "संसाधन",
    community: "समुदाय",
    english: "English",
    hindi: "हिंदी",
    loginSignup: "लॉगिन / साइन अप",
    myAccount: "मेरा अकाउंट",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    careMenu: "AarogyaShree केयर मेन्यू",
    trustedSakhi: "आपकी भरोसेमंद स्वास्थ्य सखी",
    heroTitlePrefix: "आपके लिए एक सरल, समझदार साथी",
    yourHealth: "आपके स्वास्थ्य के लिए",
    heroCopy:
      "अपने शरीर को समझें, शुरुआती संकेत पहचानें, और सुरक्षित तरीके से निजी मार्गदर्शन पाएं। भारत की हर महिला के लिए बनाया गया।",
    startHealthCheck: "स्वास्थ्य जांच शुरू करें",
    learnMore: "और जानें",
    aiInsights: "AI आधारित जानकारी",
    designedForWomen: "महिलाओं के लिए बनाया गया",
    multilingual: "कई भाषाओं की सुविधा",
    requiredFirstStep: "पहला जरूरी चरण",
    completeQuestionnaire: "पहले स्वास्थ्य questionnaire पूरा करें",
    questionnaireIntro:
      "सखी पहले कुछ आसान जरूरी सवाल पूछती है, ताकि आपका health overview आपके symptoms और history पर आधारित हो। Image upload बाद में optional support step है।",
    takesFewMinutes: "सिर्फ कुछ मिनट लगेंगे",
    privateRespectful: "निजी और सम्मानजनक",
    startQuestionnaire: "Questionnaire शुरू करें",
    assessmentFlow: "आपका assessment flow",
    oneGuidedPath: "एक guided path",
    answerRequired: "जरूरी सवालों के जवाब दें",
    answerRequiredDesc:
      "Symptoms, cycle, breast health, cervical health, mood और lifestyle.",
    addImageIfNeeded: "जरूरत हो तो image जोड़ें",
    addImageIfNeededDesc:
      "Questionnaire के बाद optional final step. आप इसे कभी भी skip कर सकती हैं।",
    getOverview: "अपना health overview पाएं",
    getOverviewDesc: "स्पष्ट next steps और suggestions के साथ सरल summary.",
    step: "चरण",
    optionalImageAfter: "Optional image upload questionnaire के बाद आता है",
    optionalImageCopy:
      "अगर आप extra AI-assisted guidance चाहती हैं तो image upload कर सकती हैं। Mobile पर camera option भी दिखेगा।",
    welcomeBack: "वापसी पर स्वागत है सखी",
    joinAarogyaShree: "AarogyaShree से जुड़ें",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड पुष्टि करें",
    login: "लॉगिन",
    signUp: "साइन अप",
    newHere: "नई हैं?",
    createAccount: "अकाउंट बनाएं",
    alreadyRegistered: "पहले से registered हैं?",
    authFailedLocal:
      "Backend login उपलब्ध नहीं है, इसलिए सखी ने यह session local रूप से save किया है।",
    yourSakhi: "आपकी सखी",
    question: "सवाल",
    of: "में से",
    complete: "पूरा",
    questionnaireComplete: "Questionnaire पूरा हुआ",
    questionnaireCompleteCopy:
      "आपके जरूरी जवाब तैयार हैं। अब आप extra AI-assisted guidance के लिए optional image जोड़ सकती हैं, या skip करके health overview देख सकती हैं।",
    requiredDone: "जरूरी सवाल पूरे हुए",
    imageOptional: "Image upload optional है",
    skipReport: "आप सीधे report देख सकती हैं",
    addOptionalImage: "Optional image जोड़ें",
    addOptionalImageCopy:
      "अगर आप अतिरिक्त guidance चाहती हैं तो image upload या capture करें।",
    continueImage: "Image step पर जाएं",
    skipImageReport: "Image skip करके report देखें",
    skipImageReportCopy:
      "Required questionnaire के आधार पर सीधे अपना health overview देखें।",
    viewReport: "मेरी report देखें",
    imageAssessment: "Image-based assessment",
    uploadSafely: "अपनी image सुरक्षित रूप से upload करें",
    uploadSafelyCopy:
      "एक clear image जोड़ें ताकि सखी gentle AI-assisted guidance दे सके। यह supportive information है, medical diagnosis नहीं।",
    addClearImage: "Clear image जोड़ें",
    clearImageCopy:
      "अच्छी lighting रखें, image steady रखें, और ऐसी कोई चीज share न करें जिससे आप comfortable न हों।",
    clickImage: "Image क्लिक करें",
    uploadImage: "Image upload करें",
    cameraMobile: "Camera capture mobile devices पर दिखता है।",
    changeImage: "Image बदलें",
    remove: "हटाएं",
    analyzeImage: "Image analyze करें",
    skipImage: "Image skip करें",
    beforeUpload: "Upload से पहले",
    imageTip1: "Clear और well-lit image इस्तेमाल करें।",
    imageTip2: "जरूरत न हो तो face या identity details शामिल न करें।",
    imageTip3:
      "Pain, discharge, bleeding, lumps या symptoms बने रहने पर doctor से सलाह लें।",
    gentleInsight: "सखी की gentle insight",
    gentleInsightCopy:
      "दी गई image के आधार पर इस placeholder preview में सब सामान्य दिखता है। अगर discomfort या बदलाव महसूस हों, तो healthcare professional से सलाह लें।",
    maintainHygiene: "साफ-सफाई बनाए रखें",
    stayHydrated: "पानी पर्याप्त पिएं",
    seekAdvice: "Symptoms बने रहें तो medical advice लें",
    continueReport: "Health Report पर जाएं",
    ageSakhi: "अपना age group बताएं ताकि सखी आपको बेहतर guide कर सके।",
    ageQuestion: "आपका age group क्या है?",
    previous: "पिछला",
    next: "अगला",
    menstrualSakhi: "आइए periods और hormonal health के बारे में बात करें।",
    regularPeriods: "क्या आपके periods regular हैं?",
    cycleLength: "आपकी usual cycle length?",
    heavyBleeding: "क्या बहुत heavy bleeding होती है?",
    missedPeriods: "2+ महीने periods miss हुए हैं? Pregnancy नहीं है?",
    yes: "हाँ",
    no: "नहीं",
    sometimes: "कभी-कभी",
    cervicalSakhi: "Cervical health से जुड़े कुछ सवाल।",
    abnormalDischarge: "क्या abnormal vaginal discharge है?",
    bleedingBetween: "Intercourse के बाद या periods के बीच bleeding?",
    pelvicPain: "Pelvic या lower abdominal pain?",
    papTest: "क्या आपने कभी Pap test कराया है?",
    never: "कभी नहीं",
    moreThan3Years: "3 साल से पहले",
    within3Years: "पिछले 3 साल में",
    breastSakhi: "आइए breast-related symptoms check करें।",
    breastLump: "क्या breast या armpit में lump महसूस हुआ?",
    breastSkin: "Breast skin या shape में बदलाव?",
    nippleDischarge: "Nipple discharge? Breast milk नहीं",
    familyHistory: "Family history of breast cancer?",
    notSure: "पता नहीं",
    generalSakhi: "Finish करने से पहले कुछ general health questions.",
    burningUrine: "Urination के समय burning sensation?",
    frequentUrge: "बार-बार urinate करने की urge?",
    feverBackPain: "Urinary problems के साथ fever या back pain?",
    moodSakhi: "Mood और daily habits के बारे में आखिरी कुछ सवाल।",
    emotionalFeeling: "इन दिनों emotionally कैसा महसूस कर रही हैं?",
    sleepQuestion: "आपकी sleep usually कैसी है?",
    exerciseQuestion: "क्या आप हफ्ते में कम से कम 3 दिन exercise करती हैं?",
    good: "अच्छा",
    stressed: "Stress",
    anxious: "Anxious",
    veryLow: "बहुत low",
    poor: "Poor",
    less21: "<21 दिन",
    days21to35: "21-35 दिन",
    more35: ">35 दिन",
    // Landing page translations
    howAarogyaHelps: "AarogyaShree आपकी कैसे मदद करता है",
    caringSpace: "आपकी भलाई के लिए एक देखभाल वाला स्थान",
    understandSymptoms: "अपने लक्षणों को समझें",
    understandSymptomsDesc: "सरल सवालों के माध्यम से बताएं कि आप कैसा महसूस कर रही हैं, और अपनी स्वास्थ्य के अनुरूप नरम मार्गदर्शन प्राप्त करें।",
    knowHealthRisks: "अपने स्वास्थ्य जोखिम जानें",
    knowHealthRisksDesc: "AI-powered विश्लेषण आपको विश्वास और देखभाल के साथ आपके जोखिम स्तर की स्पष्ट तस्वीर देता है।",
    findHelpNearby: "नजदीक मदद ढूंढें",
    findHelpNearbyDesc: "जब आपको उनकी आवश्यकता हो तो अपने पास सरकारी स्वास्थ्य केंद्र और स्क्रीनिंग सुविधाएं खोजें।",
    learnAboutBody: "अपने शरीर के बारे में जानें",
    learnAboutBodyDesc: "अपनी भाषा में विश्वसनीय स्वास्थ्य शिक्षा तक पहुंचें — सरल, सम्मानजनक और सशक्त।",
    howItSupports: "यह आपका कैसे समर्थन करता है",
    gentleGuidedCheck: "एक नरम, निर्देशित स्वास्थ्य जांच",
    shareHowYouFeel: "बताएं कि आप कैसा महसूस करती हैं",
    shareHowYouFeelDesc: "अपनी भाषा में अपने लक्षणों के बारे में सरल सवालों के जवाब दें।",
    addSimpleDetails: "सरल विवरण जोड़ें",
    addSimpleDetailsDesc: "प्रासंगिक स्वास्थ्य इतिहास साझा करें ताकि हम आपको बेहतर समझ सकें।",
    uploadImageOptional: "छवि अपलोड करें (वैकल्पिक)",
    uploadImageOptionalDesc: "यदि उपलब्ध हो, तो गहरी AI विश्लेषण के लिए एक नैदानिक छवि साझा करें।",
    getGentleGuidance: "नरम मार्गदर्शन प्राप्त करें",
    getGentleGuidanceDesc: "अगले कदमों के साथ स्पष्ट अंतर्दृष्टि प्राप्त करें — निगरानी करें, परामर्श लें, या क्लिनिक जाएं।",
    whatsInside: "अंदर क्या है",
    everythingYouNeed: "आपको जो चाहिए सब कुछ, कुछ भी भारी नहीं",
    thoughtfullyCrafted: "आपकी स्वास्थ्य यात्रा के लिए सावधानी से तैयार किए गए उपकरण सरल, स्पष्ट और हमेशा सम्मानजनक।",
    healthRiskScore: "स्वास्थ्य जोखिम स्कोर",
    healthRiskScoreDesc: "कम / मध्यम / उच्च संकेतकों के साथ दृश्य जोखिम मूल्यांकन और नरम स्पष्टीकरण।",
    cycleAwareInsights: "चक्र-जागरूक अंतर्दृष्टि",
    cycleAwareInsightsDesc: "लाइट पीरियड जागरूकता स्वास्थ्य अलर्ट के साथ जोड़ी गई, सहायक, न कि भारी।",
    nearbyClinicFinder: "नजदीक क्लिनिक फाइंडर",
    nearbyClinicFinderDesc: "नजदीकी सरकारी स्वास्थ्य केंद्र और स्क्रीनिंग सुविधाएं खोजें।",
    healthHistory: "स्वास्थ्य इतिहास",
    healthHistoryDesc: "आपकी स्क्रीनिंग, परिणामों और सिफारिशों का एक सरल समयरेखा।",
    sakhiChat: "सखी चैट",
    sakhiChatDesc: "एक शांत, बुद्धिमान चैट साथी जो सुनता है और आपको नरमी से मार्गदर्शन करता है।",
    yourDigitalSakhi: "आपकी डिजिटल सखी",
    companionWhoCares: "एक साथी जो सच में देखभाल करता है",
    sakhiDescription: "सखी सिर्फ एक चैटबॉट नहीं है — वह एक उपस्थिति है जो सुनती है, समझती है और आपके स्वास्थ्य यात्रा के माध्यम से आपको समर्थन देती है। हमेशा शांत। हमेशा दयालु।",
    listensPatiently: "धैर्य से सुनती है",
    guidesGently: "नरमी से मार्गदर्शन करती है",
    understandsConcerns: "आपकी चिंताओं को समझती है",
    speaksYourLanguage: "आपकी भाषा बोलती है",
    sakhiGreeting: "\"नमस्ते! जब भी आपको मेरी आवश्यकता हो मैं यहां हूं। आप अपने स्वास्थ्य के बारे में कुछ भी पूछ सकती हैं — मैं नरमी और ईमानदारी से मदद करने की पूरी कोशिश करूंगी। 🌸\"",
    youMightWantToAsk: "आप पूछना चाह सकती हैं:",
    earlySigns: "कौन से शुरुआती संकेत मुझे ध्यान देने चाहिए?",
    howOftenScreened: "मुझे कितनी बार स्क्रीनिंग करानी चाहिए?",
    feelingWorried: "मैं एक लक्षण के बारे में चिंतित महसूस कर रही हूं…",
    helpFindClinic: "मेरे पास एक क्लिनिक ढूंढने में मदद करें",
    builtWithCare: "देखभाल के साथ बनाया गया",
    gentleOutsideRigorousInside: "बाहर नरम, अंदर कठोर",
    behindGentleInteraction: "हर नरम बातचीत के पीछे नैदानिक सटीकता है जिस पर आप भरोसा कर सकते हैं।",
    builtOnProvenAI: "सिद्ध AI मॉडलों पर बनाया गया",
    builtOnProvenAIDesc: "हमारी स्क्रीनिंग सहकर्मी-समीक्षित चिकित्सा अनुसंधान में मान्यता प्राप्त कन्वोल्यूशनल न्यूरल नेटवर्क का उपयोग करती है।",
    clinicallyValidatedData: "नैदानिक रूप से मान्य डेटा",
    clinicallyValidatedDataDesc: "SIPaKMeD (गर्भाशय ग्रीवा) और CBIS-DDSM (स्तन) विश्वसनीय नैदानिक डेटासेट पर प्रशिक्षित।",
    worksEverywhere: "हर जगह काम करता है",
    worksEverywhereDesc: "कम कनेक्टिविटी और बुनियादी उपकरणों के लिए अनुकूलित क्योंकि स्वास्थ्य को तेज इंटरनेट की आवश्यकता नहीं होनी चाहिए।",
    trustedCompanion: "महिलाओं के स्वास्थ्य के लिए आपका विश्वसनीय साथी — व्यक्तिगत मार्गदर्शन, स्थानीय समर्थन और आपकी पसंदीदा भाषा में देखभाल प्रदान करना।",
    quickLinks: "त्वरित लिंक",
    healthAssessment: "स्वास्थ्य मूल्यांकन",
    findClinics: "क्लिनिक खोजें",
    talkToSakhi: "सखी से बात करें",
    resources: "संसाधन",
    support: "समर्थन",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    contactUs: "हमसे संपर्क करें",
    faqs: "सामान्य प्रश्न",
    allRightsReserved: "सभी अधिकार सुरक्षित।",
    copyright: `© ${new Date().getFullYear()} Aarogya Shree. सभी अधिकार सुरक्षित।`,
    footerDescription: "महिलाओं के स्वास्थ्य के लिए आपका विश्वसनीय साथी — आपकी पसंदीदा भाषा में व्यक्तिगत मार्गदर्शन, स्थानीय सहायता और देखभाल प्रदान करता है।",
    builtOnProvenAI: "सिद्ध एआई मॉडलों पर निर्मित",
    builtOnProvenAIDesc: "हमारी स्क्रीनिंग सहकर्मी-समीक्षित चिकित्सा अनुसंधान में मान्यता प्राप्त कन्वोल्यूशनल न्यूरल नेटवर्क का उपयोग करती है।",
    clinicallyValidated: "क्लिनिकली मान्य डेटा",
    clinicallyValidatedDesc: "SIPaKMeD (गर्भाशय ग्रीवा) और CBIS-DDSM (स्तन) विश्वसनीय नैदानिक डेटासेट पर प्रशिक्षित।",
    gentleOutsideRigorousInside: "बाहरी रूप से कोमल, आंतरिक रूप से कठोर",
    behindGentleInteraction: "हर कोमल बातचीत के पीछे नैदानिक सटीकता है जिस पर आप भरोसा कर सकते हैं।",
    whyTrustUs: "हम पर क्यों भरोसा करें",
    womenCentred: "महिला केंद्रित",
    womenCentredDesc: "महिलाओं द्वारा महिलाओं के लिए निर्मित — सहानुभूति, समझ और सम्मान के साथ।",
    governmentAligned: "सरकारी संरेखित",
    governmentAlignedDesc: "राष्ट्रीय स्वास्थ्य दिशानिर्देशों का पालन करता है और सरकारी स्क्रीनिंग कार्यक्रमों का समर्थन करता है।",
    expertBacked: "विशेषज्ञ समर्थित",
    expertBackedDesc: "स्वास्थ्य सेवा पेशेवरों और महिलाओं के स्वास्थ्य विशेषज्ञों के मार्गदर्शन से विकसित।",
    privacyFirst: "गोपनीयता पहले",
    privacyFirstDesc: "आपका डेटा निजी और सुरक्षित रहता है। हम व्यक्तिगत जानकारी कभी नहीं साझा करते।",
    youMightWantToAsk: "आप पूछना चाह सकते हैं:",
    sakhiGreeting: "\"नमस्ते! मैं तब भी यहां हूं जब आपकी जरूरत हो। आप अपने स्वास्थ्य के बारे में कुछ भी पूछ सकते हैं — मैं धीरे और ईमानदारी से मदद करने की पूरी कोशिश करूंगा। 🌸\"",
    yourSakhi: "आपका स्वास्थ्य साथी",
    companionWhoCares: "एक साथी जो सच में परवाह करता है",
    yourDigitalSakhi: "आपकी डिजिटल सखी",
    sakhiDescription: "सखी सिर्फ एक चैटबॉट नहीं है — वह एक उपस्थिति है जो सुनती है, समझती है और आपकी स्वास्थ्य यात्रा में आपका समर्थन करती है। हमेशा शांत। हमेशा दयालु।",
    speaksYourLanguage: "आपकी भाषा बोलती है",
    understandsConcerns: "आपकी चिंताओं को समझती है",
    guidesGently: "धीरे से मार्गदर्शन करती है",
    listensPatiently: "धैर्य से सुनती है",
    helpFindClinic: "मेरे पास एक क्लिनिक खोजने में मदद करें",
    feelingWorried: "मैं एक लक्षण के बारे में चिंतित महसूस कर रही हूं…",
    howOftenScreened: "मुझे कितनी बार स्क्रीनिंग करवानी चाहिए?",
    earlySigns: "कौन से शुरुआती संकेत मुझे ध्यान देने चाहिए?",
    whatsInside: "अंदर क्या है",
    thoughtfullyCrafted: "आपकी स्वास्थ्य यात्रा के लिए सावधानी से तैयार किए गए उपकरण सरल, स्पष्ट और हमेशा सम्मानजनक।",
    healthRiskScore: "स्वास्थ्य जोखिम स्कोर",
    healthRiskScoreDesc: "कम / मध्यम / उच्च संकेतकों के साथ दृश्य जोखिम मूल्यांकन और कोमल स्पष्टीकरण।",
    cycleAwareInsights: "चक्र-जागरूक अंतर्दृष्टि",
    cycleAwareInsightsDesc: "स्वास्थ्य अलर्ट के साथ हल्का अवधि जागरूकता, जो सहायक है न कि भारी।",
    nearbyClinicFinder: "नजदीकी क्लिनिक खोजक",
    nearbyClinicFinderDesc: "नजदीकी सरकारी स्वास्थ्य केंद्र और स्क्रीनिंग सुविधाएं खोजें।",
    healthHistory: "स्वास्थ्य इतिहास",
    healthHistoryDesc: "आपकी स्क्रीनिंग, परिणामों और सिफारिशों का एक सरल समयरेखा।",
    sakhiChat: "सखी चैट",
    sakhiChatDesc: "एक शांत, बुद्धिमान चैट साथी जो धीरे से सुनती है और मार्गदर्शन करती है।",
    howItSupports: "यह आपका समर्थन कैसे करता है",
    gentleGuidedCheck: "एक कोमल, निर्देशित स्वास्थ्य जांच",
    shareHowYouFeel: "बताएं कि आप कैसा महसूस कर रही हैं",
    shareHowYouFeelDesc: "अपनी भाषा में अपने लक्षणों के बारे में सरल प्रश्नों के जवाब दें।",
    addSimpleDetails: "सरल विवरण जोड़ें",
    addSimpleDetailsDesc: "हम आपको बेहतर ढंग से समझने के लिए प्रासंगिक स्वास्थ्य इतिहास साझा करें।",
    uploadImageOptional: "छवि अपलोड करें (वैकल्पिक)",
    uploadImageOptionalDesc: "यदि उपलब्ध हो, तो गहरी एआई विश्लेषण के लिए एक नैदानिक छवि साझा करें।",
    getGentleGuidance: "कोमल मार्गदर्शन प्राप्त करें",
    getGentleGuidanceDesc: "मॉनिटर करने, परामर्श करने या क्लिनिक जाने के लिए अगले कदमों के साथ स्पष्ट अंतर्दृष्टि प्राप्त करें।",
  },
};

export function LanguageProvider({ children }) {
  const { user, updateUserLanguage } = useAuth();
  const [language, setLanguageState] = useState(
    localStorage.getItem("sakhi_language") || "en"
  );

  useEffect(() => {
    if (user?.email) {
      const userLanguage =
        user.languagePreference ||
        localStorage.getItem(`sakhi_language_${user.email}`);

      if (userLanguage && userLanguage !== language) {
        setLanguageState(userLanguage);
      }
    }
  }, [user]);

  const setLanguage = (nextLanguage) => {
    setLanguageState(nextLanguage);
    localStorage.setItem("sakhi_language", nextLanguage);

    if (user?.email) {
      localStorage.setItem(`sakhi_language_${user.email}`, nextLanguage);
      updateUserLanguage?.(nextLanguage);
    }
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language]?.[key] || translations.en[key] || key,
    }),
    [language, user]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
