import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "./AuthContext";

const LanguageContext = createContext();

const translations = {
  en: {
    assessment: "Assessment",
    dashboard: "Dashboard",
    askSakhi: "Ask Sakhi",
    clinics: "Clinics",
    resources: "Resources",
    community: "Community",
    english: "English",
    hindi: "Hindi",
    marathi: "Marathi",
    telugu: "Telugu",
    bengali: "Bengali",
    loginSignup: "Login / Sign Up",
    myAccount: "My Account",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    careMenu: "AarogyaShree care menu",
    trustedSakhi: "Your trusted health sakhi",
    heroTitlePrefix: "A gentle, intelligent companion for",
    yourHealth: "Your Health",
    heroCopy:
      "Understand your body, detect early signs, and get guidance in a safe and personal way. Built for every woman across India.",
    startHealthCheck: "Start My Health Check",
    learnMore: "Learn More",
    aiInsights: "AI-powered insights",
    designedForWomen: "Designed for women",
    multilingual: "Multilingual support",
    requiredFirstStep: "Required first step",
    completeQuestionnaire: "Complete your health questionnaire first",
    questionnaireIntro:
      "Sakhi starts with simple required questions so your health overview is based on your symptoms and history. Image upload comes later as an optional support step.",
    takesFewMinutes: "Takes only a few minutes",
    privateRespectful: "Private and respectful",
    startQuestionnaire: "Start Questionnaire",
    assessmentFlow: "Your assessment flow",
    oneGuidedPath: "One guided path",
    answerRequired: "Answer required questions",
    answerRequiredDesc:
      "Symptoms, cycle, breast health, cervical health, mood, and lifestyle.",
    addImageIfNeeded: "Add image if needed",
    addImageIfNeededDesc:
      "Optional final step after the questionnaire. Skip it anytime.",
    healthDashboard: "Health dashboard",
    welcomeDashboard: "Welcome",
    dashboardIntro:
      "Your latest test results, health trends, and next actions update here after each completed assessment.",
    imageAnalysis: "Image analysis",
    assessmentsMetric: "Assessments",
    averageRiskMetric: "Average risk",
    attentionFlagsMetric: "Attention flags",
    lastCheckMetric: "Last check",
    none: "None",
    latestAssessmentResult: "Latest assessment result",
    latestAssessmentCopy:
      "This section reflects the newest saved response from the assessment service.",
    loadingLatestResult: "Loading latest result...",
    hormonalRiskLabel: "Hormonal / PCOS",
    cervicalHealthLabel: "Cervical health",
    breastHealthLabel: "Breast health",
    urinaryHealthLabel: "Urinary health",
    emotionalWellbeingLabel: "Emotional wellbeing",
    recommendedNextSteps: "Recommended next steps",
    quickActions: "Quick actions",
    talkToSakhiCopy: "Ask a health question privately.",
    findClinicsCopy: "Locate nearby care and screening support.",
    findClinicsNearYou: "Find clinics and counselling near you",
    nearbyClinicsIntro: "Search trusted maternal and women’s health clinics close to your location.",
    usingLocation: "Using location:",
    findingYourArea: "Finding your area…",
    useMyLocation: "Use my location",
    searchClinicsPlaceholder: "Search clinics, services, or nearby hospitals",
    yourCurrentArea: "Your current area",
    showingCareOptionsNearYourCurrentArea: "Showing care options near your current area.",
    showingOptionsNear: "Showing options near",
    detectingLocation: "Detecting your location…",
    locationNotSupported: "Location is not supported in this browser.",
    locationPermissionUnavailable: "Location permission is unavailable.",
    liveMapResults: "Live map results",
    estimatedNearbyResults: "Estimated nearby results",
    allDistances: "All distances",
    within5Km: "Within 5 km",
    within15Km: "Within 15 km",
    within25Km: "Within 25 km",
    within50Km: "Within 50 km",
    allLanguages: "All languages",
    all: "All",
    hospital: "Hospital",
    clinic: "Clinic",
    refresh: "Refresh",
    search: "Search",
    noClinicsFound: "No clinics found",
    tryAdjustingFilters: "Try adjusting filters or expanding the distance range.",
    resetFilters: "Reset filters",
    emergencyContacts: "Emergency contacts",
    womenHelpline: "Women helpline",
    twentyFourSevenSupport: "24/7 support",
    healthHelpline: "Health helpline",
    medicalAssistance: "Medical assistance",
    ambulance: "Ambulance",
    emergencyTransport: "Emergency transport",
    updateProfile: "Update profile",
    assessmentHistory: "Assessment history",
    assessmentHistoryIntro: "Recent saved results from your completed tests.",
    viewProfileTimeline: "View profile timeline",
    noAssessmentsSaved: "No assessments have been saved yet.",
    questionnaire: "questionnaire",
    noAssessmentYet: "No assessment yet",
    completeQuestionnaireOnce:
      "Complete the questionnaire once and your latest result, recommendations, and dashboard trend will appear here.",
    startNow: "Start now",
    addImageIfNeededDesc:
      "Optional final step after the questionnaire. Skip it anytime.",
    getOverview: "Get your health overview",
    getOverviewDesc: "A gentle summary with clear next steps and suggestions.",
    step: "Step",
    optionalImageAfter: "Optional image upload comes after the questionnaire",
    optionalImageCopy:
      "You can upload an image if you want extra AI-assisted guidance. On mobile, Sakhi will also show a camera option.",
    welcomeBack: "Welcome Back Sakhi",
    joinAarogyaShree: "Join AarogyaShree",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    login: "Login",
    signUp: "Sign Up",
    newHere: "New here?",
    createAccount: "Create account",
    alreadyRegistered: "Already registered?",
    authFailedLocal:
      "Backend login is unavailable, so Sakhi saved this session locally.",
    yourSakhi: "Your Sakhi",
    question: "Question",
    of: "of",
    complete: "Complete",
    questionnaireComplete: "Questionnaire complete",
    questionnaireCompleteCopy:
      "Your required answers are ready. You can now add an optional image for extra AI-assisted guidance, or skip it and view your health overview.",
    requiredDone: "Required questions completed",
    imageOptional: "Image upload is optional",
    skipReport: "You can skip to your report",
    addOptionalImage: "Add optional image",
    addOptionalImageCopy:
      "Upload or capture an image if you want additional guidance.",
    continueImage: "Continue to image step",
    skipImageReport: "Skip image and view report",
    skipImageReportCopy:
      "Go directly to your health overview based on the required questionnaire.",
    viewReport: "View my report",
    imageAssessment: "Image-based assessment",
    uploadSafely: "Upload your image safely",
    uploadSafelyCopy:
      "Add a clear image so Sakhi can provide gentle AI-assisted guidance. This is supportive information, not a medical diagnosis.",
    addClearImage: "Add a clear image",
    clearImageCopy:
      "Use good lighting, keep the image steady, and avoid sharing anything you are not comfortable uploading.",
    clickImage: "Click Image",
    uploadImage: "Upload Image",
    cameraMobile: "Camera capture appears on mobile devices.",
    changeImage: "Change image",
    remove: "Remove",
    analyzeImage: "Analyze Image",
    skipImage: "Skip Image",
    beforeUpload: "Before you upload",
    imageTip1: "Use a clear, well-lit image.",
    imageTip2: "Avoid including face or identity details if not needed.",
    imageTip3:
      "Consult a doctor for pain, discharge, bleeding, lumps, or symptoms that persist.",
    gentleInsight: "Sakhi's gentle insight",
    gentleInsightCopy:
      "Based on the image provided, everything appears generally normal in this placeholder preview. If you are experiencing discomfort or changes, consider consulting a healthcare professional.",
    maintainHygiene: "Maintain proper hygiene",
    stayHydrated: "Stay hydrated",
    seekAdvice: "Seek medical advice if symptoms persist",
    continueReport: "Continue to Health Report",
    ageSakhi: "Let me know your age group so I can guide you better.",
    ageQuestion: "What is your age group?",
    previous: "Previous",
    next: "Next",
    menstrualSakhi: "Let's talk about your periods and hormonal health.",
    regularPeriods: "Are your periods regular?",
    cycleLength: "Your usual cycle length?",
    heavyBleeding: "Do you have very heavy bleeding?",
    missedPeriods: "Missed periods for 2+ months (not pregnant)?",
    yes: "Yes",
    no: "No",
    sometimes: "Sometimes",
    cervicalSakhi: "Some questions related to cervical health.",
    abnormalDischarge: "Abnormal vaginal discharge?",
    bleedingBetween: "Bleeding after intercourse or between periods?",
    pelvicPain: "Pelvic or lower abdominal pain?",
    papTest: "Have you ever had a Pap test?",
    never: "Never",
    moreThan3Years: "More than 3 years ago",
    within3Years: "Within last 3 years",
    breastSakhi: "Let's check for any breast-related symptoms.",
    breastLump: "Have you felt any lump in breast or armpit?",
    breastSkin: "Any change in breast skin or shape?",
    nippleDischarge: "Any nipple discharge (not breast milk)?",
    familyHistory: "Family history of breast cancer?",
    notSure: "Not sure",
    generalSakhi: "Some general health questions before we finish.",
    burningUrine: "Burning sensation while urinating?",
    frequentUrge: "Frequent urge to urinate?",
    feverBackPain: "Fever or back pain with urinary problems?",
    moodSakhi: "Last few questions about your mood and daily habits.",
    emotionalFeeling: "How are you feeling emotionally these days?",
    sleepQuestion: "How is your sleep usually?",
    exerciseQuestion: "Do you exercise at least 3 days a week?",
    good: "Good",
    stressed: "Stressed",
    anxious: "Anxious",
    veryLow: "Very low",
    poor: "Poor",
    less21: "<21 days",
    days21to35: "21-35 days",
    more35: ">35 days",
    everythingYouNeed: "Everything you need for a guided health check",
    builtWithCare: "Built with care",
    howAarogyaHelps: "How AarogyaShree helps",
    caringSpace: "A caring space for every question",
    aiHealthCompanion: "AI health companion",
    askSakhiSubtitle: "Gentle guidance for symptoms, screening, and next steps.",
    askSakhiDisclaimer:
      "Sakhi can help you understand possible next steps, but she cannot diagnose or replace a doctor.",
    sakhiWelcome:
      "Hello, I am Sakhi. You can ask me about symptoms, reports, screening, or when to see a doctor.",
    sakhiRestart: "Hi again. What would you like to talk about now?",
    typeHealthQuestion: "Type your health question...",
    sendHint: "Press Enter to send. Shift+Enter for new line.",
    clearChat: "Clear chat",
    sakhiTyping: "Sakhi is typing",
    periodsAndPcos: "Periods and PCOS",
    breastHealth: "Breast health",
    cervicalScreening: "Cervical screening",
    urinaryProblems: "Urinary problems",
    explainMyReport: "Explain my report",
  },
  hi: {
    assessment: "मूल्यांकन",
    dashboard: "डैशबोर्ड",
    askSakhi: "सखी से पूछें",
    clinics: "क्लिनिक",
    resources: "संसाधन",
    community: "समुदाय",
    english: "English",
    hindi: "हिंदी",
    loginSignup: "लॉगिन / साइन अप",
    myAccount: "मेरा अकाउंट",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    careMenu: "AarogyaShree केयर मेन्यू",
    trustedSakhi: "आपकी भरोसेमंद स्वास्थ्य सखी",
    heroTitlePrefix: "आपके लिए एक सरल, समझदार साथी",
    yourHealth: "आपके स्वास्थ्य के लिए",
    heroCopy:
      "अपने शरीर को समझें, शुरुआती संकेत पहचानें, और सुरक्षित तरीके से निजी मार्गदर्शन पाएं। भारत की हर महिला के लिए बनाया गया।",
    startHealthCheck: "स्वास्थ्य जांच शुरू करें",
    learnMore: "और जानें",
    aiInsights: "AI आधारित जानकारी",
    designedForWomen: "महिलाओं के लिए बनाया गया",
    multilingual: "कई भाषाओं की सुविधा",
    requiredFirstStep: "पहला जरूरी चरण",
    completeQuestionnaire: "पहले स्वास्थ्य questionnaire पूरा करें",
    questionnaireIntro:
      "सखी पहले कुछ आसान जरूरी सवाल पूछती है, ताकि आपका health overview आपके symptoms और history पर आधारित हो। Image upload बाद में optional support step है।",
    takesFewMinutes: "सिर्फ कुछ मिनट लगेंगे",
    privateRespectful: "निजी और सम्मानजनक",
    startQuestionnaire: "Questionnaire शुरू करें",
    assessmentFlow: "आपका assessment flow",
    oneGuidedPath: "एक guided path",
    answerRequired: "जरूरी सवालों के जवाब दें",
    answerRequiredDesc:
      "Symptoms, cycle, breast health, cervical health, mood और lifestyle.",
    addImageIfNeeded: "जरूरत हो तो image जोड़ें",
    addImageIfNeededDesc:
      "Questionnaire के बाद optional final step. आप इसे कभी भी skip कर सकती हैं।",
    healthDashboard: "स्वास्थ्य डैशबोर्ड",
    welcomeDashboard: "स्वागतम",
    dashboardIntro:
      "आपके नवीनतम परीक्षण परिणाम, स्वास्थ्य प्रवृत्तियाँ, और अगले कदम हर पूर्ण किए गए आकलन के बाद यहाँ अपडेट होंगे।",
    imageAnalysis: "इमेज विश्लेषण",
    assessmentsMetric: "मूल्यांकन",
    averageRiskMetric: "औसत जोखिम",
    attentionFlagsMetric: "ध्यान संकेत",
    lastCheckMetric: "अंतिम जांच",
    none: "कोई नहीं",
    latestAssessmentResult: "नवीनतम आकलन परिणाम",
    latestAssessmentCopy:
      "यह अनुभाग आकलन सेवा से नवीनतम सेव किए गए उत्तर को दर्शाता है।",
    loadingLatestResult: "नवीनतम परिणाम लोड हो रहा है...",
    hormonalRiskLabel: "हार्मोनल / PCOS",
    cervicalHealthLabel: "सर्वाइकल स्वास्थ्य",
    breastHealthLabel: "स्तन स्वास्थ्य",
    urinaryHealthLabel: "मूत्र संबंधी स्वास्थ्य",
    emotionalWellbeingLabel: "भावनात्मक कल्याण",
    recommendedNextSteps: "सिफारिश किए गए अगले कदम",
    quickActions: "त्वरित कार्य",
    talkToSakhiCopy: "निजी रूप से एक स्वास्थ्य प्रश्न पूछें।",
    findClinicsCopy: "नज़दीकी देखभाल और स्क्रीनिंग सहायता खोजें।",
    findClinicsNearYou: "अपने नजदीकी क्लिनिक खोजें",
    nearbyClinicsIntro: "अपने स्थान के पास विश्वसनीय स्वास्थ्य क्लिनिक खोजें।",
    usingLocation: "स्थान उपयोग कर रहे हैं:",
    findingYourArea: "आपके क्षेत्र को ढूंढ रहे हैं…",
    useMyLocation: "मेरा स्थान उपयोग करें",
    searchClinicsPlaceholder: "क्लिनिक, सेवाएँ, या अस्पताल खोजें",
    yourCurrentArea: "आपका वर्तमान क्षेत्र",
    showingCareOptionsNearYourCurrentArea: "आपके वर्तमान क्षेत्र के पास देखभाल विकल्प दिखा रहे हैं।",
    showingOptionsNear: "के पास विकल्प दिखा रहे हैं",
    detectingLocation: "आपका स्थान पता लगाया जा रहा है…",
    locationNotSupported: "इस ब्राउज़र में स्थान समर्थित नहीं है।",
    locationPermissionUnavailable: "स्थान अनुमति उपलब्ध नहीं है।",
    liveMapResults: "लाइव मानचित्र परिणाम",
    estimatedNearbyResults: "अनुमानित नजदीकी परिणाम",
    allDistances: "सभी दूरी",
    within5Km: "5 किमी के भीतर",
    within15Km: "15 किमी के भीतर",
    within25Km: "25 किमी के भीतर",
    within50Km: "50 किमी के भीतर",
    allLanguages: "सभी भाषाएँ",
    all: "सभी",
    hospital: "अस्पताल",
    clinic: "क्लिनिक",
    refresh: "रिफ्रेश",
    search: "खोजें",
    noClinicsFound: "कोई क्लिनिक नहीं मिले",
    tryAdjustingFilters: "फ़िल्टर समायोजित करने या दूरी बढ़ाने का प्रयास करें।",
    resetFilters: "फ़िल्टर रीसेट करें",
    emergencyContacts: "आपातकालीन संपर्क",
    womenHelpline: "महिला हेल्पलाइन",
    twentyFourSevenSupport: "24/7 सहायता",
    healthHelpline: "स्वास्थ्य हेल्पलाइन",
    medicalAssistance: "चिकित्सा सहायता",
    ambulance: "एम्बुलेंस",
    emergencyTransport: "आपातकालीन परिवहन",
    updateProfile: "प्रोफ़ाइल अपडेट करें",
    assessmentHistory: "आकलन इतिहास",
    assessmentHistoryIntro: "आपके पूर्ण किए गए परीक्षणों से हाल के संग्रहीत परिणाम।",
    viewProfileTimeline: "प्रोफ़ाइल टाइमलाइन देखें",
    noAssessmentsSaved: "कोई आकलन अभी तक संग्रहित नहीं किया गया है।",
    questionnaire: "questionnaire",
    noAssessmentYet: "अभी कोई आकलन नहीं",
    completeQuestionnaireOnce:
      "एक बार प्रश्नावली पूरा करें और आपका नवीनतम परिणाम, सिफारिशें, और डैशबोर्ड प्रवृत्ति यहाँ दिखाई देंगी।",
    startNow: "अब शुरू करें",
    getOverview: "अपना health overview पाएं",
    getOverviewDesc: "स्पष्ट next steps और suggestions के साथ सरल summary.",
    step: "चरण",
    optionalImageAfter: "Optional image upload questionnaire के बाद आता है",
    optionalImageCopy:
      "अगर आप extra AI-assisted guidance चाहती हैं तो image upload कर सकती हैं। Mobile पर camera option भी दिखेगा।",
    welcomeBack: "वापसी पर स्वागत है सखी",
    joinAarogyaShree: "AarogyaShree से जुड़ें",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड पुष्टि करें",
    login: "लॉगिन",
    signUp: "साइन अप",
    newHere: "नई हैं?",
    createAccount: "अकाउंट बनाएं",
    alreadyRegistered: "पहले से registered हैं?",
    authFailedLocal:
      "Backend login उपलब्ध नहीं है, इसलिए सखी ने यह session local रूप से save किया है।",
    yourSakhi: "आपकी सखी",
    question: "सवाल",
    of: "में से",
    complete: "पूरा",
    questionnaireComplete: "Questionnaire पूरा हुआ",
    questionnaireCompleteCopy:
      "आपके जरूरी जवाब तैयार हैं। अब आप extra AI-assisted guidance के लिए optional image जोड़ सकती हैं, या skip करके health overview देख सकती हैं।",
    requiredDone: "जरूरी सवाल पूरे हुए",
    imageOptional: "Image upload optional है",
    skipReport: "आप सीधे report देख सकती हैं",
    addOptionalImage: "Optional image जोड़ें",
    addOptionalImageCopy:
      "अगर आप अतिरिक्त guidance चाहती हैं तो image upload या capture करें।",
    continueImage: "Image step पर जाएं",
    skipImageReport: "Image skip करके report देखें",
    skipImageReportCopy:
      "Required questionnaire के आधार पर सीधे अपना health overview देखें।",
    viewReport: "मेरी report देखें",
    imageAssessment: "Image-based assessment",
    uploadSafely: "अपनी image सुरक्षित रूप से upload करें",
    uploadSafelyCopy:
      "एक clear image जोड़ें ताकि सखी gentle AI-assisted guidance दे सके। यह supportive information है, medical diagnosis नहीं।",
    addClearImage: "Clear image जोड़ें",
    clearImageCopy:
      "अच्छी lighting रखें, image steady रखें, और ऐसी कोई चीज share न करें जिससे आप comfortable न हों।",
    clickImage: "Image क्लिक करें",
    uploadImage: "Image upload करें",
    cameraMobile: "Camera capture mobile devices पर दिखता है।",
    changeImage: "Image बदलें",
    remove: "हटाएं",
    analyzeImage: "Image analyze करें",
    skipImage: "Image skip करें",
    beforeUpload: "Upload से पहले",
    imageTip1: "Clear और well-lit image इस्तेमाल करें।",
    imageTip2: "जरूरत न हो तो face या identity details शामिल न करें।",
    imageTip3:
      "Pain, discharge, bleeding, lumps या symptoms बने रहने पर doctor से सलाह लें।",
    gentleInsight: "सखी की gentle insight",
    gentleInsightCopy:
      "दी गई image के आधार पर इस placeholder preview में सब सामान्य दिखता है। अगर discomfort या बदलाव महसूस हों, तो healthcare professional से सलाह लें।",
    maintainHygiene: "साफ-सफाई बनाए रखें",
    stayHydrated: "पानी पर्याप्त पिएं",
    seekAdvice: "Symptoms बने रहें तो medical advice लें",
    continueReport: "Health Report पर जाएं",
    ageSakhi: "अपना age group बताएं ताकि सखी आपको बेहतर guide कर सके।",
    ageQuestion: "आपका age group क्या है?",
    previous: "पिछला",
    next: "अगला",
    menstrualSakhi: "आइए periods और hormonal health के बारे में बात करें।",
    regularPeriods: "क्या आपके periods regular हैं?",
    cycleLength: "आपकी usual cycle length?",
    heavyBleeding: "क्या बहुत heavy bleeding होती है?",
    missedPeriods: "2+ महीने periods miss हुए हैं? Pregnancy नहीं है?",
    yes: "हाँ",
    no: "नहीं",
    sometimes: "कभी-कभी",
    cervicalSakhi: "Cervical health से जुड़े कुछ सवाल।",
    abnormalDischarge: "क्या abnormal vaginal discharge है?",
    bleedingBetween: "Intercourse के बाद या periods के बीच bleeding?",
    pelvicPain: "Pelvic या lower abdominal pain?",
    papTest: "क्या आपने कभी Pap test कराया है?",
    never: "कभी नहीं",
    moreThan3Years: "3 साल से पहले",
    within3Years: "पिछले 3 साल में",
    breastSakhi: "आइए breast-related symptoms check करें।",
    breastLump: "क्या breast या armpit में lump महसूस हुआ?",
    breastSkin: "Breast skin या shape में बदलाव?",
    nippleDischarge: "Nipple discharge? Breast milk नहीं",
    familyHistory: "Family history of breast cancer?",
    notSure: "पता नहीं",
    generalSakhi: "Finish करने से पहले कुछ general health questions.",
    burningUrine: "Urination के समय burning sensation?",
    frequentUrge: "बार-बार urinate करने की urge?",
    feverBackPain: "Urinary problems के साथ fever या back pain?",
    moodSakhi: "Mood और daily habits के बारे में आखिरी कुछ सवाल।",
    emotionalFeeling: "इन दिनों emotionally कैसा महसूस कर रही हैं?",
    sleepQuestion: "आपकी sleep usually कैसी है?",
    exerciseQuestion: "क्या आप हफ्ते में कम से कम 3 दिन exercise करती हैं?",
    good: "अच्छा",
    stressed: "Stress",
    anxious: "Anxious",
    veryLow: "बहुत low",
    poor: "Poor",
    less21: "<21 दिन",
    days21to35: "21-35 दिन",
    more35: ">35 दिन",
    // Landing page translations
    howAarogyaHelps: "AarogyaShree आपकी कैसे मदद करता है",
    caringSpace: "आपकी भलाई के लिए एक देखभाल वाला स्थान",
    understandSymptoms: "अपने लक्षणों को समझें",
    understandSymptomsDesc: "सरल सवालों के माध्यम से बताएं कि आप कैसा महसूस कर रही हैं, और अपनी स्वास्थ्य के अनुरूप नरम मार्गदर्शन प्राप्त करें।",
    knowHealthRisks: "अपने स्वास्थ्य जोखिम जानें",
    knowHealthRisksDesc: "AI-powered विश्लेषण आपको विश्वास और देखभाल के साथ आपके जोखिम स्तर की स्पष्ट तस्वीर देता है।",
    findHelpNearby: "नजदीक मदद ढूंढें",
    findHelpNearbyDesc: "जब आपको उनकी आवश्यकता हो तो अपने पास सरकारी स्वास्थ्य केंद्र और स्क्रीनिंग सुविधाएं खोजें।",
    learnAboutBody: "अपने शरीर के बारे में जानें",
    learnAboutBodyDesc: "अपनी भाषा में विश्वसनीय स्वास्थ्य शिक्षा तक पहुंचें — सरल, सम्मानजनक और सशक्त।",
    howItSupports: "यह आपका कैसे समर्थन करता है",
    gentleGuidedCheck: "एक नरम, निर्देशित स्वास्थ्य जांच",
    shareHowYouFeel: "बताएं कि आप कैसा महसूस करती हैं",
    shareHowYouFeelDesc: "अपनी भाषा में अपने लक्षणों के बारे में सरल सवालों के जवाब दें।",
    addSimpleDetails: "सरल विवरण जोड़ें",
    addSimpleDetailsDesc: "प्रासंगिक स्वास्थ्य इतिहास साझा करें ताकि हम आपको बेहतर समझ सकें।",
    uploadImageOptional: "छवि अपलोड करें (वैकल्पिक)",
    uploadImageOptionalDesc: "यदि उपलब्ध हो, तो गहरी AI विश्लेषण के लिए एक नैदानिक छवि साझा करें।",
    getGentleGuidance: "नरम मार्गदर्शन प्राप्त करें",
    getGentleGuidanceDesc: "अगले कदमों के साथ स्पष्ट अंतर्दृष्टि प्राप्त करें — निगरानी करें, परामर्श लें, या क्लिनिक जाएं।",
    whatsInside: "अंदर क्या है",
    everythingYouNeed: "आपको जो चाहिए सब कुछ, कुछ भी भारी नहीं",
    thoughtfullyCrafted: "आपकी स्वास्थ्य यात्रा के लिए सावधानी से तैयार किए गए उपकरण सरल, स्पष्ट और हमेशा सम्मानजनक।",
    healthRiskScore: "स्वास्थ्य जोखिम स्कोर",
    healthRiskScoreDesc: "कम / मध्यम / उच्च संकेतकों के साथ दृश्य जोखिम मूल्यांकन और नरम स्पष्टीकरण।",
    cycleAwareInsights: "चक्र-जागरूक अंतर्दृष्टि",
    cycleAwareInsightsDesc: "लाइट पीरियड जागरूकता स्वास्थ्य अलर्ट के साथ जोड़ी गई, सहायक, न कि भारी।",
    nearbyClinicFinder: "नजदीक क्लिनिक फाइंडर",
    nearbyClinicFinderDesc: "नजदीकी सरकारी स्वास्थ्य केंद्र और स्क्रीनिंग सुविधाएं खोजें।",
    healthHistory: "स्वास्थ्य इतिहास",
    healthHistoryDesc: "आपकी स्क्रीनिंग, परिणामों और सिफारिशों का एक सरल समयरेखा।",
    sakhiChat: "सखी चैट",
    sakhiChatDesc: "एक शांत, बुद्धिमान चैट साथी जो सुनता है और आपको नरमी से मार्गदर्शन करता है।",
    yourDigitalSakhi: "आपकी डिजिटल सखी",
    companionWhoCares: "एक साथी जो सच में देखभाल करता है",
    sakhiDescription: "सखी सिर्फ एक चैटबॉट नहीं है — वह एक उपस्थिति है जो सुनती है, समझती है और आपके स्वास्थ्य यात्रा के माध्यम से आपको समर्थन देती है। हमेशा शांत। हमेशा दयालु।",
    listensPatiently: "धैर्य से सुनती है",
    guidesGently: "नरमी से मार्गदर्शन करती है",
    understandsConcerns: "आपकी चिंताओं को समझती है",
    speaksYourLanguage: "आपकी भाषा बोलती है",
    sakhiGreeting: "\"नमस्ते! जब भी आपको मेरी आवश्यकता हो मैं यहां हूं। आप अपने स्वास्थ्य के बारे में कुछ भी पूछ सकती हैं — मैं नरमी और ईमानदारी से मदद करने की पूरी कोशिश करूंगी। 🌸\"",
    youMightWantToAsk: "आप पूछना चाह सकती हैं:",
    earlySigns: "कौन से शुरुआती संकेत मुझे ध्यान देने चाहिए?",
    howOftenScreened: "मुझे कितनी बार स्क्रीनिंग करानी चाहिए?",
    feelingWorried: "मैं एक लक्षण के बारे में चिंतित महसूस कर रही हूं…",
    helpFindClinic: "मेरे पास एक क्लिनिक ढूंढने में मदद करें",
    builtWithCare: "देखभाल के साथ बनाया गया",
    gentleOutsideRigorousInside: "बाहर नरम, अंदर कठोर",
    behindGentleInteraction: "हर नरम बातचीत के पीछे नैदानिक सटीकता है जिस पर आप भरोसा कर सकते हैं।",
    builtOnProvenAI: "सिद्ध AI मॉडलों पर बनाया गया",
    builtOnProvenAIDesc: "हमारी स्क्रीनिंग सहकर्मी-समीक्षित चिकित्सा अनुसंधान में मान्यता प्राप्त कन्वोल्यूशनल न्यूरल नेटवर्क का उपयोग करती है।",
    clinicallyValidatedData: "नैदानिक रूप से मान्य डेटा",
    clinicallyValidatedDataDesc: "SIPaKMeD (गर्भाशय ग्रीवा) और CBIS-DDSM (स्तन) विश्वसनीय नैदानिक डेटासेट पर प्रशिक्षित।",
    worksEverywhere: "हर जगह काम करता है",
    worksEverywhereDesc: "कम कनेक्टिविटी और बुनियादी उपकरणों के लिए अनुकूलित क्योंकि स्वास्थ्य को तेज इंटरनेट की आवश्यकता नहीं होनी चाहिए।",
    trustedCompanion: "महिलाओं के स्वास्थ्य के लिए आपका विश्वसनीय साथी — व्यक्तिगत मार्गदर्शन, स्थानीय समर्थन और आपकी पसंदीदा भाषा में देखभाल प्रदान करना।",
    quickLinks: "त्वरित लिंक",
    healthAssessment: "स्वास्थ्य मूल्यांकन",
    findClinics: "क्लिनिक खोजें",
    talkToSakhi: "सखी से बात करें",
    resources: "संसाधन",
    support: "समर्थन",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    contactUs: "हमसे संपर्क करें",
    faqs: "सामान्य प्रश्न",
    allRightsReserved: "सभी अधिकार सुरक्षित।",
    copyright: `© ${new Date().getFullYear()} Aarogya Shree. सभी अधिकार सुरक्षित।`,
    footerDescription: "महिलाओं के स्वास्थ्य के लिए आपका विश्वसनीय साथी — आपकी पसंदीदा भाषा में व्यक्तिगत मार्गदर्शन, स्थानीय सहायता और देखभाल प्रदान करता है।",
    builtOnProvenAI: "सिद्ध एआई मॉडलों पर निर्मित",
    builtOnProvenAIDesc: "हमारी स्क्रीनिंग सहकर्मी-समीक्षित चिकित्सा अनुसंधान में मान्यता प्राप्त कन्वोल्यूशनल न्यूरल नेटवर्क का उपयोग करती है।",
    clinicallyValidated: "क्लिनिकली मान्य डेटा",
    clinicallyValidatedDesc: "SIPaKMeD (गर्भाशय ग्रीवा) और CBIS-DDSM (स्तन) विश्वसनीय नैदानिक डेटासेट पर प्रशिक्षित।",
    gentleOutsideRigorousInside: "बाहरी रूप से कोमल, आंतरिक रूप से कठोर",
    behindGentleInteraction: "हर कोमल बातचीत के पीछे नैदानिक सटीकता है जिस पर आप भरोसा कर सकते हैं।",
    whyTrustUs: "हम पर क्यों भरोसा करें",
    womenCentred: "महिला केंद्रित",
    womenCentredDesc: "महिलाओं द्वारा महिलाओं के लिए निर्मित — सहानुभूति, समझ और सम्मान के साथ।",
    governmentAligned: "सरकारी संरेखित",
    governmentAlignedDesc: "राष्ट्रीय स्वास्थ्य दिशानिर्देशों का पालन करता है और सरकारी स्क्रीनिंग कार्यक्रमों का समर्थन करता है।",
    expertBacked: "विशेषज्ञ समर्थित",
    expertBackedDesc: "स्वास्थ्य सेवा पेशेवरों और महिलाओं के स्वास्थ्य विशेषज्ञों के मार्गदर्शन से विकसित।",
    privacyFirst: "गोपनीयता पहले",
    privacyFirstDesc: "आपका डेटा निजी और सुरक्षित रहता है। हम व्यक्तिगत जानकारी कभी नहीं साझा करते।",
    youMightWantToAsk: "आप पूछना चाह सकते हैं:",
    sakhiGreeting: "\"नमस्ते! मैं तब भी यहां हूं जब आपकी जरूरत हो। आप अपने स्वास्थ्य के बारे में कुछ भी पूछ सकते हैं — मैं धीरे और ईमानदारी से मदद करने की पूरी कोशिश करूंगा। 🌸\"",
    yourSakhi: "आपका स्वास्थ्य साथी",
    companionWhoCares: "एक साथी जो सच में परवाह करता है",
    yourDigitalSakhi: "आपकी डिजिटल सखी",
    sakhiDescription: "सखी सिर्फ एक चैटबॉट नहीं है — वह एक उपस्थिति है जो सुनती है, समझती है और आपकी स्वास्थ्य यात्रा में आपका समर्थन करती है। हमेशा शांत। हमेशा दयालु।",
    speaksYourLanguage: "आपकी भाषा बोलती है",
    understandsConcerns: "आपकी चिंताओं को समझती है",
    guidesGently: "धीरे से मार्गदर्शन करती है",
    listensPatiently: "धैर्य से सुनती है",
    helpFindClinic: "मेरे पास एक क्लिनिक खोजने में मदद करें",
    feelingWorried: "मैं एक लक्षण के बारे में चिंतित महसूस कर रही हूं…",
    howOftenScreened: "मुझे कितनी बार स्क्रीनिंग करवानी चाहिए?",
    earlySigns: "कौन से शुरुआती संकेत मुझे ध्यान देने चाहिए?",
    whatsInside: "अंदर क्या है",
    thoughtfullyCrafted: "आपकी स्वास्थ्य यात्रा के लिए सावधानी से तैयार किए गए उपकरण सरल, स्पष्ट और हमेशा सम्मानजनक।",
    healthRiskScore: "स्वास्थ्य जोखिम स्कोर",
    healthRiskScoreDesc: "कम / मध्यम / उच्च संकेतकों के साथ दृश्य जोखिम मूल्यांकन और कोमल स्पष्टीकरण।",
    cycleAwareInsights: "चक्र-जागरूक अंतर्दृष्टि",
    cycleAwareInsightsDesc: "स्वास्थ्य अलर्ट के साथ हल्का अवधि जागरूकता, जो सहायक है न कि भारी।",
    nearbyClinicFinder: "नजदीकी क्लिनिक खोजक",
    nearbyClinicFinderDesc: "नजदीकी सरकारी स्वास्थ्य केंद्र और स्क्रीनिंग सुविधाएं खोजें।",
    healthHistory: "स्वास्थ्य इतिहास",
    healthHistoryDesc: "आपकी स्क्रीनिंग, परिणामों और सिफारिशों का एक सरल समयरेखा।",
    sakhiChat: "सखी चैट",
    sakhiChatDesc: "एक शांत, बुद्धिमान चैट साथी जो धीरे से सुनती है और मार्गदर्शन करती है।",
    howItSupports: "यह आपका समर्थन कैसे करता है",
    gentleGuidedCheck: "एक कोमल, निर्देशित स्वास्थ्य जांच",
    shareHowYouFeel: "बताएं कि आप कैसा महसूस कर रही हैं",
    shareHowYouFeelDesc: "अपनी भाषा में अपने लक्षणों के बारे में सरल प्रश्नों के जवाब दें।",
    addSimpleDetails: "सरल विवरण जोड़ें",
    addSimpleDetailsDesc: "हम आपको बेहतर ढंग से समझने के लिए प्रासंगिक स्वास्थ्य इतिहास साझा करें।",
    uploadImageOptional: "छवि अपलोड करें (वैकल्पिक)",
    uploadImageOptionalDesc: "यदि उपलब्ध हो, तो गहरी एआई विश्लेषण के लिए एक नैदानिक छवि साझा करें।",
    getGentleGuidance: "कोमल मार्गदर्शन प्राप्त करें",
    getGentleGuidanceDesc: "मॉनिटर करने, परामर्श करने या क्लिनिक जाने के लिए अगले कदमों के साथ स्पष्ट अंतर्दृष्टि प्राप्त करें।",
  },
};

export const languageOptions = [
  { code: "en", labelKey: "english", aiName: "English" },
  { code: "hi", labelKey: "hindi", aiName: "Hindi" },
  { code: "mr", labelKey: "marathi", aiName: "Marathi" },
  { code: "te", labelKey: "telugu", aiName: "Telugu" },
  { code: "bn", labelKey: "bengali", aiName: "Bengali" },
];

const regionalTranslations = {
  mr: {
    assessment: "मूल्यांकन",
    dashboard: "डॅशबोर्ड",
    askSakhi: "सखीला विचारा",
    clinics: "क्लिनिक",
    resources: "संसाधने",
    community: "समुदाय",
    english: "English",
    hindi: "हिंदी",
    marathi: "मराठी",
    telugu: "तेलुगू",
    bengali: "बंगाली",
    loginSignup: "लॉग इन / साइन अप",
    myAccount: "माझे खाते",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    logout: "लॉग आउट",
    careMenu: "AarogyaShree काळजी मेनू",
    trustedSakhi: "तुमची विश्वासू आरोग्य सखी",
    heroTitlePrefix: "तुमच्या आरोग्यासाठी एक सौम्य, बुद्धिमान साथीदार",
    yourHealth: "तुमचे आरोग्य",
    heroCopy: "तुमचे शरीर समजून घ्या, सुरुवातीची लक्षणे ओळखा आणि सुरक्षित, वैयक्तिक मार्गदर्शन मिळवा. भारतातील प्रत्येक स्त्रीसाठी तयार.",
    startHealthCheck: "माझी आरोग्य तपासणी सुरू करा",
    learnMore: "अधिक जाणून घ्या",
    aiInsights: "AI आधारित माहिती",
    designedForWomen: "महिलांसाठी डिझाइन केलेले",
    multilingual: "अनेक भाषांचा आधार",
    everythingYouNeed: "मार्गदर्शित आरोग्य तपासणीसाठी आवश्यक सर्व काही",
    builtWithCare: "काळजीपूर्वक तयार केलेले",
    howAarogyaHelps: "AarogyaShree कशी मदत करते",
    caringSpace: "प्रत्येक प्रश्नासाठी काळजी घेणारी जागा",
    startQuestionnaire: "प्रश्नावली सुरू करा",
    takesFewMinutes: "फक्त काही मिनिटे लागतात",
    privateRespectful: "खाजगी आणि आदरपूर्वक",
    yes: "होय",
    no: "नाही",
    sometimes: "कधी कधी",
    previous: "मागील",
    next: "पुढे",
    question: "प्रश्न",
    of: "पैकी",
    complete: "पूर्ण",
    yourSakhi: "तुमची सखी",
    fullName: "पूर्ण नाव",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड पुष्टी करा",
    login: "लॉग इन",
    signUp: "साइन अप",
    welcomeBack: "परत स्वागत आहे सखी",
    joinAarogyaShree: "AarogyaShree मध्ये सामील व्हा",
    newHere: "नवीन आहात?",
    createAccount: "खाते तयार करा",
    alreadyRegistered: "आधीच नोंदणी केली आहे?",
    healthDashboard: "स्वास्थ्य डॅशबोर्ड",
    welcomeDashboard: "स्वागत आहे",
    dashboardIntro: "आपल्या नवीनतम चाचणी परिणाम, आरोग्य प्रवृत्ती आणि पुढील क्रिया प्रत्येक पूर्ण केलेल्या मूल्यांकनानंतर येथे अद्यतनित होतील.",
    imageAnalysis: "प्रतिमा विश्लेषण",
    assessmentsMetric: "मूल्यमापन",
    averageRiskMetric: "सरासरी जोखीम",
    attentionFlagsMetric: "लक्ष देण्यासारखे चिन्हे",
    lastCheckMetric: "शेवटचे तपास",
    none: "काहीही नाही",
    latestAssessmentResult: "नवीनतम मूल्यांकन निकाल",
    latestAssessmentCopy: "हा विभाग मूल्यांकन सेवेमधील नवीनतम जतन केलेला प्रतिसाद दर्शवतो.",
    loadingLatestResult: "नवीनतम निकाल लोड केला जात आहे...",
    hormonalRiskLabel: "हार्मोनल / PCOS",
    cervicalHealthLabel: "गर्भाशय आरोग्य",
    breastHealthLabel: "स्तन आरोग्य",
    urinaryHealthLabel: "लघवीचे आरोग्य",
    emotionalWellbeingLabel: "भावनिक कल्याण",
    recommendedNextSteps: "शिफारस केलेले पुढील पाऊळ",
    quickActions: "त्वरित कृती",
    talkToSakhiCopy: "खाजगीपणे आरोग्य प्रश्न विचार करा.",
    findClinicsCopy: "जवळच्या काळजी आणि स्क्रीनिंग सहाय्याचा शोध घ्या.",
    findClinicsNearYou: "तुमच्या जवळचे क्लिनिक शोधा",
    nearbyClinicsIntro: "तुमच्या ठिकाणाजवळ विश्वसनीय आरोग्य क्लिनिक शोधा.",
    usingLocation: "स्थान वापरत आहोत:",
    findingYourArea: "तुमचा परिसर शोधत आहोत…",
    useMyLocation: "माझे स्थान वापरा",
    searchClinicsPlaceholder: "क्लिनिक, सेवा किंवा हॉस्पिटल शोधा",
    yourCurrentArea: "तुमचे सध्याचे क्षेत्र",
    showingCareOptionsNearYourCurrentArea: "तुमच्या सध्याच्या क्षेत्राजवळील काळजी पर्याय दाखवत आहोत.",
    showingOptionsNear: "चासत्राजवळ पर्याय दाखवत आहोत",
    detectingLocation: "तुमचे स्थान शोधत आहे…",
    locationNotSupported: "हा ब्राउझर स्थानाला समर्थन देत नाही.",
    locationPermissionUnavailable: "स्थान परवानगी उपलब्ध नाही.",
    liveMapResults: "लाइव्ह नकाशा परिणाम",
    estimatedNearbyResults: "अनुमानित जवळचे परिणाम",
    allDistances: "सर्व अंतर",
    within5Km: "5 किमीच्या आत",
    within15Km: "15 किमीच्या आत",
    within25Km: "25 किमीच्या आत",
    within50Km: "50 किमीच्या आत",
    allLanguages: "सर्व भाषा",
    all: "सर्व",
    hospital: "रुग्णालय",
    clinic: "क्लिनिक",
    refresh: "रिफ्रेश",
    search: "शोधा",
    noClinicsFound: "कोणतेही क्लिनिक सापडले नाही",
    tryAdjustingFilters: "फिल्टर्स समायोजित करा किंवा अंतर वाढवा.",
    resetFilters: "फिल्टर रीसेट करा",
    emergencyContacts: "आपत्कालीन संपर्क",
    womenHelpline: "स्त्री हेल्पलाइन",
    twentyFourSevenSupport: "24/7 समर्थन",
    healthHelpline: "आरोग्य हेल्पलाइन",
    medicalAssistance: "वैद्यकीय सहाय्य",
    ambulance: "ऍम्ब्युलन्स",
    emergencyTransport: "आपत्कालीन वाहतूक",
    updateProfile: "प्रोफाइल अद्यतनित करा",
    assessmentHistory: "मूल्यमापन इतिहास",
    assessmentHistoryIntro: "आपल्या पूर्ण झालेल्या चाचण्यांमधील अलीकडील जतन केलेले निकाल.",
    viewProfileTimeline: "प्रोफाइल टाइमलाइन पहा",
    noAssessmentsSaved: "अद्याप कोणतेही मूल्यमापन जतन केलेले नाही.",
    questionnaire: "प्रश्नावली",
    noAssessmentYet: "अद्याप कोणतेही मूल्यांकन नाही",
    completeQuestionnaireOnce: "एकदा प्रश्नावली पूर्ण करा आणि आपला नवीनतम निकाल, शिफारसी आणि डॅशबोर्ड प्रवृत्ती येथे दिसेल.",
    startNow: "आता सुरू करा",
    findClinics: "क्लिनिक शोधा",
    talkToSakhi: "सखीशी बोला",
    quickLinks: "जलद दुवे",
    support: "मदत",
    privacyPolicy: "गोपनीयता धोरण",
    termsOfService: "सेवेच्या अटी",
    contactUs: "आमच्याशी संपर्क साधा",
    faqs: "सामान्य प्रश्न",
    footerDescription: "महिलांच्या आरोग्यासाठी तुमचा विश्वासू साथीदार, वैयक्तिक मार्गदर्शन आणि स्थानिक मदतीसह.",
    copyright: `© ${new Date().getFullYear()} Aarogya Shree. सर्व हक्क राखीव.`,
    aiHealthCompanion: "AI आरोग्य साथी",
    askSakhiSubtitle: "लक्षणे, तपासणी आणि पुढील पावलांसाठी सौम्य मार्गदर्शन.",
    askSakhiDisclaimer: "सखी पुढील पावले समजून घेण्यास मदत करू शकते, पण ती निदान करू शकत नाही किंवा डॉक्टरांची जागा घेऊ शकत नाही.",
    sakhiWelcome: "नमस्कार, मी सखी आहे. तुम्ही मला लक्षणे, रिपोर्ट, तपासणी किंवा डॉक्टरांकडे कधी जायचे याबद्दल विचारू शकता.",
    sakhiRestart: "पुन्हा नमस्कार. आता तुम्हाला कशाबद्दल बोलायचे आहे?",
    typeHealthQuestion: "तुमचा आरोग्य प्रश्न लिहा...",
    sendHint: "पाठवण्यासाठी Enter दाबा. नवीन ओळीसाठी Shift+Enter.",
    clearChat: "चॅट साफ करा",
    sakhiTyping: "सखी टाइप करत आहे",
    periodsAndPcos: "पाळी आणि PCOS",
    breastHealth: "स्तन आरोग्य",
    cervicalScreening: "गर्भाशय मुख तपासणी",
    urinaryProblems: "मूत्र समस्या",
    explainMyReport: "माझा रिपोर्ट समजवा",
  },
  te: {
    assessment: "అంచనా",
    dashboard: "డాష్‌బోర్డ్",
    askSakhi: "సఖిని అడగండి",
    clinics: "క్లినిక్‌లు",
    resources: "వనరులు",
    community: "సముదాయం",
    english: "English",
    hindi: "హిందీ",
    marathi: "మరాఠీ",
    telugu: "తెలుగు",
    bengali: "బెంగాలీ",
    loginSignup: "లాగిన్ / సైన్ అప్",
    myAccount: "నా ఖాతా",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్‌లు",
    logout: "లాగ్ అవుట్",
    careMenu: "AarogyaShree సంరక్షణ మెనూ",
    trustedSakhi: "మీ నమ్మకమైన ఆరోగ్య సఖి",
    heroTitlePrefix: "మీ ఆరోగ్యానికి సున్నితమైన, తెలివైన తోడుడు",
    yourHealth: "మీ ఆరోగ్యం",
    heroCopy: "మీ శరీరాన్ని అర్థం చేసుకోండి, ప్రారంభ సూచనలను గుర్తించండి మరియు సురక్షితమైన వ్యక్తిగత మార్గదర్శనం పొందండి. భారతదేశంలోని ప్రతి మహిళ కోసం రూపొందించబడింది.",
    startHealthCheck: "నా ఆరోగ్య తనిఖీ ప్రారంభించండి",
    learnMore: "మరింత తెలుసుకోండి",
    aiInsights: "AI ఆధారిత సూచనలు",
    designedForWomen: "మహిళల కోసం రూపొందించబడింది",
    multilingual: "బహుభాషా మద్దతు",
    everythingYouNeed: "మార్గదర్శిత ఆరోగ్య తనిఖీకి అవసరమైన ప్రతిదీ",
    builtWithCare: "శ్రద్ధతో నిర్మించబడింది",
    howAarogyaHelps: "AarogyaShree ఎలా సహాయపడుతుంది",
    caringSpace: "ప్రతి ప్రశ్నకు ఆదరణ కలిగిన స్థలం",
    startQuestionnaire: "ప్రశ్నావళి ప్రారంభించండి",
    takesFewMinutes: "కొన్ని నిమిషాలే పడుతుంది",
    privateRespectful: "గోప్యంగా మరియు గౌరవంగా",
    yes: "అవును",
    no: "కాదు",
    sometimes: "కొన్నిసార్లు",
    previous: "మునుపటి",
    next: "తదుపరి",
    question: "ప్రశ్న",
    of: "లో",
    complete: "పూర్తి",
    yourSakhi: "మీ సఖి",
    fullName: "పూర్తి పేరు",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    confirmPassword: "పాస్‌వర్డ్ నిర్ధారించండి",
    login: "లాగిన్",
    signUp: "సైన్ అప్",
    welcomeBack: "మళ్లీ స్వాగతం సఖి",
    joinAarogyaShree: "AarogyaShree లో చేరండి",
    newHere: "కొత్తవారా?",
    createAccount: "ఖాతా సృష్టించండి",
    alreadyRegistered: "ఇప్పటికే నమోదు అయ్యారా?",
    healthDashboard: "ఆరోగ్య డాష్‌బోర్డ్",
    welcomeDashboard: "స్వాగతం",
    dashboardIntro: "మీ తాజా పరీక్షా ఫలితాలు, ఆరోగ్య ధోరణులు మరియు తదుపరి చర్యలు ప్రతి పూర్తి చేయబడిన మూల్యాంకనానికి తరువాత ఇక్కడ నవీకరించబడతాయి.",
    imageAnalysis: "చిత్ర విశ్లేషణ",
    assessmentsMetric: "మూల్యాంకనాలు",
    averageRiskMetric: "సగటు ప్రమాదం",
    attentionFlagsMetric: "దృష్టి అవసరమైన సూచనలు",
    lastCheckMetric: "చివరి తనిఖీ",
    none: "ఏవీ కాదు",
    latestAssessmentResult: "తాజా మూల్యాంకన ఫలితం",
    latestAssessmentCopy: "ఈ విభాగం మూల్యాంకన సేవ నుండి తాజా సేవ్ చేయబడిన ప్రతిస్పందనను ప్రతిబింబిస్తుంది.",
    loadingLatestResult: "తాజా ఫలితం లోడ్ చేయబడుతోంది...",
    hormonalRiskLabel: "హార్మోనల్ / PCOS",
    cervicalHealthLabel: "సర్వికల్ ఆరోగ్యం",
    breastHealthLabel: "స్తన ఆరోగ్యం",
    urinaryHealthLabel: "మూత్ర ఆరోగ్యం",
    emotionalWellbeingLabel: "భావోద్వేగ సంక్షేమం",
    recommendedNextSteps: "సిఫార్సు చేయబడిన తదుపరి చర్యలు",
    quickActions: "త్వరిత చర్యలు",
    talkToSakhiCopy: "ఒక ఆరోగ్య ప్రశ్నను ప్రత్యేకంగా అడగండి.",
    findClinicsCopy: "నిజానికి దగ్గర్లో సేవ మరియు స్క్రీనింగ్ మద్దతును కనుగొనండి.",
    findClinicsNearYou: "మీకు సమీపంలోని క్లినిక్స్‌ను కనుగొనండి",
    nearbyClinicsIntro: "మీ స్థలం దగ్గర నమ్మకమైన ఆరోగ్య క్లినిక్స్‌ను శోధించండి.",
    usingLocation: "స్థానాన్ని ఉపయోగిస్తున్నారు:",
    findingYourArea: "మీ ప్రాంతాన్ని కనుగొంటున్నాం…",
    useMyLocation: "నా స్థానాన్ని ఉపయోగించండి",
    searchClinicsPlaceholder: "క్లినిక్స్, సేవలు లేదా ఆసుపత్రిని శోధించండి",
    yourCurrentArea: "మీ ప్రస్తుత ప్రాంతం",
    showingCareOptionsNearYourCurrentArea: "మీ ప్రస్తుత ప్రాంతానికి సమీపంలో సేవల ఎంపికలను చూపిస్తాం.",
    showingOptionsNear: "సమీపంలో ఎంపికలను చూపిస్తున్నాం",
    detectingLocation: "మీ ప్రాంతాన్ని గుర్తిస్తున్నారు…",
    locationNotSupported: "ఈ బ్రౌజర్‌లో స్థానం మద్దతు లభించదు.",
    locationPermissionUnavailable: "స్థానం అనుమతి అందుబాటులో లేదు.",
    liveMapResults: "లైవ్ మ్యాప్ ఫలితాలు",
    estimatedNearbyResults: "అంచనా సమీప ఫలితాలు",
    allDistances: "అన్ని దూరాలు",
    within5Km: "5 కిమీ లోపల",
    within15Km: "15 కిమీ లోపల",
    within25Km: "25 కిమీ లోపల",
    within50Km: "50 కిమీ లోపల",
    allLanguages: "అన్నీ భాషలు",
    all: "అన్నది",
    hospital: "హాస్పిటల్",
    clinic: "క్లినిక్",
    refresh: "రిఫ్రెష్",
    search: "శోధించండి",
    noClinicsFound: "ఏ క్లినిక్స్ కనబడలేదు",
    tryAdjustingFilters: "ఫిల్టర్లు సర్దుబాటు చేయడానికి లేదా దూరాన్ని పెంచడానికి ప్రయత్నించండి.",
    resetFilters: "ఫిల్టర్‌లను మళ్లీ ఏర్పాటు చేయండి",
    emergencyContacts: "అత్యవసర సంప్రదింపులు",
    womenHelpline: "మహిళల హెల్ప్‌లైన్",
    twentyFourSevenSupport: "24/7 మద్దతు",
    healthHelpline: "ఆరోగ్య హెల్ప్‌లైన్",
    medicalAssistance: "వైద్య సహాయం",
    ambulance: "ఆంబులెన్స్",
    emergencyTransport: "అత్యవసర రవాణా",
    updateProfile: "ప్రొఫైల్ నవీకరణ",
    updateProfileCopy: "మీ వ్యక్తిగత ఆరోగ్య సందర్భాన్ని తాజా ఉంచండి.",
    noTrendYet: "ఇప్పటికే సరైన ధోరణి లేదు",
    assessmentHistory: "మూల్యాంకన చరిత్ర",
    assessmentHistoryIntro: "మీ పూర్తి చేసిన పరీక్షల నుండి ఇటీవల సేవ్ చేయబడిన ఫలితాలు.",
    viewProfileTimeline: "ప్రొఫైల్ టైమ్‌లైన్ చూడండి",
    noAssessmentsSaved: "ఇప్పవ్వగా ఏ మూల్యాంకనాలను సేవ్ చేయలేదు.",
    questionnaire: "ప్రశ్నావళి",
    noAssessmentYet: "ఇప్పటికే ఏ మూల్యాంకనం లేదు",
    completeQuestionnaireOnce: "ఒకసారి ప్రశ్నావళిని పూర్తి చేయండి మరియు మీ తాజా ఫలితం, సిఫార్సులు మరియు డ్యాష్‌బోర్డ్ ధోరణి ఇక్కడ కనిపిస్తాయి.",
    startNow: "ఇప్పుడే ప్రారంభించండి",
    findClinics: "క్లినిక్‌లను కనుగొనండి",
    talkToSakhi: "సఖితో మాట్లాడండి",
    quickLinks: "త్వరిత లింకులు",
    support: "సహాయం",
    privacyPolicy: "గోప్యతా విధానం",
    termsOfService: "సేవా నిబంధనలు",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    faqs: "తరచుగా అడిగే ప్రశ్నలు",
    footerDescription: "మహిళల ఆరోగ్యానికి మీ నమ్మకమైన తోడుడు, వ్యక్తిగత మార్గదర్శనం మరియు స్థానిక సహాయంతో.",
    copyright: `© ${new Date().getFullYear()} Aarogya Shree. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.`,
    aiHealthCompanion: "AI ఆరోగ్య తోడుడు",
    askSakhiSubtitle: "లక్షణాలు, స్క్రీనింగ్ మరియు తదుపరి చర్యలకు సున్నితమైన మార్గదర్శనం.",
    askSakhiDisclaimer: "సఖి తదుపరి చర్యలను అర్థం చేసుకోవడంలో సహాయం చేస్తుంది, కానీ నిర్ధారణ చేయదు లేదా వైద్యుడిని భర్తీ చేయదు.",
    sakhiWelcome: "నమస్తే, నేను సఖిని. లక్షణాలు, రిపోర్టులు, స్క్రీనింగ్ లేదా డాక్టర్‌ను ఎప్పుడు కలవాలో మీరు అడగవచ్చు.",
    sakhiRestart: "మళ్లీ నమస్తే. ఇప్పుడు మీరు ఏ విషయం గురించి మాట్లాడాలనుకుంటున్నారు?",
    typeHealthQuestion: "మీ ఆరోగ్య ప్రశ్నను టైప్ చేయండి...",
    sendHint: "పంపడానికి Enter నొక్కండి. కొత్త లైన్ కోసం Shift+Enter.",
    clearChat: "చాట్ క్లియర్ చేయండి",
    sakhiTyping: "సఖి టైప్ చేస్తోంది",
    periodsAndPcos: "పీరియడ్స్ మరియు PCOS",
    breastHealth: "స్తన ఆరోగ్యం",
    cervicalScreening: "సర్వికల్ స్క్రీనింగ్",
    urinaryProblems: "మూత్ర సమస్యలు",
    explainMyReport: "నా రిపోర్ట్ వివరించండి",
  },
  bn: {
    assessment: "মূল্যায়ন",
    dashboard: "ড্যাশবোর্ড",
    askSakhi: "সখীকে জিজ্ঞাসা করুন",
    clinics: "ক্লিনিক",
    resources: "রিসোর্স",
    community: "কমিউনিটি",
    english: "English",
    hindi: "হিন্দি",
    marathi: "মারাঠি",
    telugu: "তেলুগু",
    bengali: "বাংলা",
    loginSignup: "লগ ইন / সাইন আপ",
    myAccount: "আমার অ্যাকাউন্ট",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    logout: "লগ আউট",
    careMenu: "AarogyaShree কেয়ার মেনু",
    trustedSakhi: "আপনার বিশ্বস্ত স্বাস্থ্য সখী",
    heroTitlePrefix: "আপনার স্বাস্থ্যের জন্য কোমল, বুদ্ধিমান সঙ্গী",
    yourHealth: "আপনার স্বাস্থ্য",
    heroCopy: "নিজের শরীর বুঝুন, প্রাথমিক লক্ষণ চিনুন এবং নিরাপদ ব্যক্তিগত নির্দেশনা পান। ভারতের প্রতিটি নারীর জন্য তৈরি।",
    startHealthCheck: "আমার স্বাস্থ্য পরীক্ষা শুরু করুন",
    learnMore: "আরও জানুন",
    aiInsights: "AI-চালিত তথ্য",
    designedForWomen: "নারীদের জন্য তৈরি",
    multilingual: "বহুভাষিক সহায়তা",
    everythingYouNeed: "নির্দেশিত স্বাস্থ্য পরীক্ষার জন্য প্রয়োজনীয় সবকিছু",
    builtWithCare: "যত্ন নিয়ে তৈরি",
    howAarogyaHelps: "AarogyaShree কীভাবে সাহায্য করে",
    caringSpace: "প্রতিটি প্রশ্নের জন্য যত্নশীল জায়গা",
    startQuestionnaire: "প্রশ্নাবলি শুরু করুন",
    takesFewMinutes: "মাত্র কয়েক মিনিট লাগে",
    privateRespectful: "ব্যক্তিগত এবং সম্মানজনক",
    yes: "হ্যাঁ",
    no: "না",
    sometimes: "কখনও কখনও",
    previous: "আগের",
    next: "পরের",
    question: "প্রশ্ন",
    of: "এর মধ্যে",
    complete: "সম্পূর্ণ",
    yourSakhi: "আপনার সখী",
    fullName: "পুরো নাম",
    email: "ইমেল",
    password: "পাসওয়ার্ড",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    login: "লগ ইন",
    signUp: "সাইন আপ",
    welcomeBack: "ফিরে আসায় স্বাগতম সখী",
    joinAarogyaShree: "AarogyaShree-তে যোগ দিন",
    newHere: "নতুন?",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    alreadyRegistered: "আগেই নিবন্ধিত?",
    healthDashboard: "স্বাস্থ্য ড্যাশবোর্ড",
    welcomeDashboard: "স্বাগতম",
    dashboardIntro: "আপনার সর্বশেষ পরীক্ষা ফলাফল, স্বাস্থ্য প্রবণতা এবং পরবর্তী পদক্ষেপ প্রতিটি সম্পূর্ণ মূল্যায়নের পরে এখানে আপডেট হবে।",
    imageAnalysis: "চিত্র বিশ্লেষণ",
    assessmentsMetric: "মূল্যায়ন",
    averageRiskMetric: "গড় ঝুঁকি",
    attentionFlagsMetric: "মনোযোগের ফ্ল্যাগ",
    lastCheckMetric: "সর্বশেষ পরীক্ষা",
    none: "কোনো নেই",
    latestAssessmentResult: "সর্বশেষ মূল্যায়ন ফলাফল",
    latestAssessmentCopy: "এই বিভাগটি মূল্যায়ন পরিষেবা থেকে সর্বশেষ সংরক্ষিত প্রতিক্রিয়া প্রতিফলিত করে।",
    loadingLatestResult: "সর্বশেষ ফলাফল লোড করছে...",
    hormonalRiskLabel: "হার্মোনাল / PCOS",
    cervicalHealthLabel: "সার্ভিকাল স্বাস্থ্য",
    breastHealthLabel: "স্তন স্বাস্থ্য",
    urinaryHealthLabel: "মূত্রজনিত স্বাস্থ্য",
    emotionalWellbeingLabel: "ভৌগোলিক মঙ্গল",
    recommendedNextSteps: "প্রস্তাবিত পরবর্তী পদক্ষেপ",
    quickActions: "দ্রুত অ্যাকশন",
    talkToSakhiCopy: "ব্যক্তিগতভাবে একটি স্বাস্থ্য প্রশ্ন জিজ্ঞাসা করুন।",
    findClinicsCopy: "নিকটবর্তী যত্ন ও স্ক্রিনিং সহায়তা খুঁজুন।",
    findClinicsNearYou: "আপনার কাছে ক্লিনিকগুলিকে সন্ধান করুন",
    nearbyClinicsIntro: "আপনার অবস্থানের কাছে নির্ভরযোগ্য স্বাস্থ্য ক্লিনিকগুলি সন্ধান করুন।",
    usingLocation: "অবস্থান ব্যবহার করা হচ্ছে:",
    findingYourArea: "আপনার অঞ্চল সন্ধান করা হচ্ছে…",
    useMyLocation: "আমার অবস্থান ব্যবহার করুন",
    searchClinicsPlaceholder: "ক্লিনিক, পরিষেবা বা হাসপাতাল অনুসন্ধান করুন",
    yourCurrentArea: "আপনার বর্তমান এলাকা",
    showingCareOptionsNearYourCurrentArea: "আপনার বর্তমান এলাকার কাছে অপশন দেখানো হচ্ছে।",
    showingOptionsNear: "কাছাকাছি অপশন দেখানো হচ্ছে",
    detectingLocation: "আপনার স্থান সনাক্ত করছিঃ…",
    locationNotSupported: "এই ব্রাউজারে অবস্থান সমর্থিত নয়।",
    locationPermissionUnavailable: "অবস্থান অনুমতি উপলব্ধ নয়।",
    liveMapResults: "লাইভ মানচিত্র ফলাফল",
    estimatedNearbyResults: "আনুমানিক কাছাকাছি ফলাফল",
    allDistances: "সমস্ত দূরত্ব",
    within5Km: "5 কিমি এর মধ্যে",
    within15Km: "15 কিমি এর মধ্যে",
    within25Km: "25 কিমি এর মধ্যে",
    within50Km: "50 কিমি এর মধ্যে",
    allLanguages: "সমস্ত ভাষা",
    all: "সব",
    hospital: "হাসপাতাল",
    clinic: "ক্লিনিক",
    refresh: "রিফ্রেশ",
    search: "অনুসন্ধান",
    noClinicsFound: "কোন ক্লিনিক পাওয়া যায়নি",
    tryAdjustingFilters: "ফিল্টার সামঞ্জস্য করুন বা দূরত্ব বাড়ানোর চেষ্টা করুন।",
    resetFilters: "ফিল্টার রিসেট করুন",
    emergencyContacts: "জরুরি যোগাযোগ",
    womenHelpline: "মহিলা হেল্পলাইন",
    twentyFourSevenSupport: "24/7 সহায়তা",
    healthHelpline: "স্বাস্থ্য হেল্পলাইন",
    medicalAssistance: "চিকিৎসার সহায়তা",
    ambulance: "অ্যাম্বুলেন্স",
    emergencyTransport: "জরুরি পরিবহন",
    updateProfile: "প্রোফাইল আপডেট করুন",
    assessmentHistory: "মূল্যায়ন ইতিহাস",
    assessmentHistoryIntro: "আপনার সম্পূর্ণ পরীক্ষার থেকে সাম্প্রতিক সংরক্ষিত ফলাফল।",
    viewProfileTimeline: "প্রোফাইল টাইমলাইন দেখুন",
    noAssessmentsSaved: "এখনও কোনও মূল্যায়ন সংরক্ষিত হয়নি।",
    questionnaire: "প্রশ্নমালা",
    noAssessmentYet: "এখনও কোনও মূল্যায়ন নেই",
    completeQuestionnaireOnce: "একবার প্রশ্নমালা সম্পন্ন করুন এবং আপনার সর্বশেষ ফলাফল, সুপারিশ এবং ড্যাশবোর্ড প্রবণতা এখানে প্রদর্শিত হবে।",
    startNow: "এখনই শুরু করুন",
    findClinics: "ক্লিনিক খুঁজুন",
    talkToSakhi: "সখীর সঙ্গে কথা বলুন",
    quickLinks: "দ্রুত লিঙ্ক",
    support: "সহায়তা",
    privacyPolicy: "গোপনীয়তা নীতি",
    termsOfService: "পরিষেবার শর্তাবলি",
    contactUs: "যোগাযোগ করুন",
    faqs: "সাধারণ প্রশ্ন",
    footerDescription: "নারীদের স্বাস্থ্যের জন্য আপনার বিশ্বস্ত সঙ্গী, ব্যক্তিগত নির্দেশনা এবং স্থানীয় সহায়তাসহ।",
    copyright: `© ${new Date().getFullYear()} Aarogya Shree. সর্বস্বত্ব সংরক্ষিত।`,
    aiHealthCompanion: "AI স্বাস্থ্য সঙ্গী",
    askSakhiSubtitle: "লক্ষণ, স্ক্রিনিং এবং পরবর্তী পদক্ষেপের জন্য কোমল নির্দেশনা।",
    askSakhiDisclaimer: "সখী সম্ভাব্য পরবর্তী পদক্ষেপ বুঝতে সাহায্য করতে পারে, কিন্তু রোগ নির্ণয় করতে পারে না বা ডাক্তারের বিকল্প নয়।",
    sakhiWelcome: "নমস্কার, আমি সখী। আপনি লক্ষণ, রিপোর্ট, স্ক্রিনিং বা কখন ডাক্তার দেখাবেন তা নিয়ে প্রশ্ন করতে পারেন।",
    sakhiRestart: "আবার নমস্কার। এখন আপনি কী নিয়ে কথা বলতে চান?",
    typeHealthQuestion: "আপনার স্বাস্থ্য প্রশ্ন লিখুন...",
    sendHint: "পাঠাতে Enter চাপুন। নতুন লাইনের জন্য Shift+Enter.",
    clearChat: "চ্যাট মুছুন",
    sakhiTyping: "সখী টাইপ করছে",
    periodsAndPcos: "পিরিয়ড এবং PCOS",
    breastHealth: "স্তন স্বাস্থ্য",
    cervicalScreening: "সার্ভিকাল স্ক্রিনিং",
    urinaryProblems: "মূত্র সমস্যা",
    explainMyReport: "আমার রিপোর্ট ব্যাখ্যা করুন",
  },
};

const supportedLanguageCodes = languageOptions.map((item) => item.code);

function humanizeKey(key) {
  return String(key)
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

export function getLanguageName(code) {
  return languageOptions.find((item) => item.code === code)?.aiName || "English";
}

function translate(language, key) {
  return (
    regionalTranslations[language]?.[key] ||
    translations[language]?.[key] ||
    translations.en[key] ||
    humanizeKey(key)
  );
}

export function LanguageProvider({ children }) {
  const { user, updateUserLanguage } = useAuth();
  const [language, setLanguageState] = useState(() => {
    const savedLanguage = localStorage.getItem("sakhi_language") || "en";
    return supportedLanguageCodes.includes(savedLanguage) ? savedLanguage : "en";
  });

  useEffect(() => {
    if (user?.email) {
      const userLanguage =
        user.languagePreference ||
        localStorage.getItem(`sakhi_language_${user.email}`);

      if (
        userLanguage &&
        supportedLanguageCodes.includes(userLanguage) &&
        userLanguage !== language
      ) {
        setLanguageState(userLanguage);
      }
    }
  }, [user]);

  const setLanguage = (nextLanguage) => {
    const safeLanguage = supportedLanguageCodes.includes(nextLanguage)
      ? nextLanguage
      : "en";

    setLanguageState(safeLanguage);
    localStorage.setItem("sakhi_language", safeLanguage);

    if (user?.email) {
      localStorage.setItem(`sakhi_language_${user.email}`, safeLanguage);
      updateUserLanguage?.(safeLanguage);
    }
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      languageName: getLanguageName(language),
      languageOptions,
      t: (key) => translate(language, key),
    }),
    [language, user]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
